### ISSUE TITLE
fasterxml.jackson-core 2.3.2 dependency

### ISSUE THREAD

**Issue by ABMBelgrade** [duosecurity/duo_universal_java#16]
Hi, im having this issue when trying to call `duoClient.exchangeAuthorizationCodeFor2FAResult`
`Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.readerFor(Lcom/fasterxml/jackson/databind/JavaType;)Lcom/fasterxml/jackson/databind/ObjectReader;`

Googling i found that the readerFor method was introduced in version 2.6 of fasterxml

Is there a way to update the fasterxml dependency or am i going in the wrong way?
Thnx

**Comment by ABMBelgrade** [comment]
Update, i removed duo-universal-sdk dependency, cleaned everything i could find, added it agan, and stil it has 2.3.2 fasterxml... i can see in pom it should be 2.12.4, but i just cant figure out why it not...

![image](https://user-images.githubusercontent.com/41011745/133439524-5b53bd4f-ed33-4f50-ab72-f7296b80959e.png)

**Comment by AaronAtDuo** [comment]
@ABMBelgrade We've run into a similar problem before.  I suspect that somewhere else in your project there's a dependency, or dependency of a dependency, etc. that pulls in a lower version of jackson-core.

So I think you are running into a similar problem as https://stackoverflow.com/questions/38139597/maven-loads-wrong-version-of-dependency/38139885

You can give `mvn dependency:tree` a try to see if it turns up anything, but reportedly that doesn't always list all transitive dependencies, so you might have to do some digging to determine where the old version is coming from.

Unfortunately, I don't think there's much that can be done with the Duo Universal client to work around this.  Even older versions are still using a fairly recent version of jackson-core.  Hopefully you can find out what other dependency is causing this conflict and update that one.  Let us know what you find and maybe some ideas will come up.

**Comment by ABMBelgrade** [comment]
You are correct. It looks like hibernate-validatior module uses fasterxml... Thanks for the help, i will checkout your link to try  and resolve this issue.

**Comment by AaronAtDuo** [comment]
@ABMBelgrade Were you able to resolve your dependency conflict?

**Comment by ABMBelgrade** [comment]
> @ABMBelgrade Were you able to resolve your dependency conflict?

Nah, since the whole project is outdated, we decided to migrate it to Angular 2.0+ (from AngularJS)

**Comment by AaronAtDuo** [comment]
Good luck!  Let us know if you run into any other problems and thanks for using Duo.

**Comment by ABMBelgrade** [comment]
> Good luck! Let us know if you run into any other problems and thanks for using Duo.

Tnx for the support!
