### ISSUE TITLE
Dependency version conflict

### ISSUE THREAD

**Issue by philsmart** [duosecurity/duo_universal_java#18]
In v1.1.3 the okhttp3 logging-interceptor changed to v4.9.1 which depends on okhttp v4.9.1. However, retrofit v2.9.0 is still at okhttp v3.14.9. It seems to all work, but maybe the logging-interceptor should be held back a version?

**Comment by AaronAtDuo** [comment]
Argh... I thought I had tracked all the conflicts down.  Thanks for mentioning this, we'll take a look and see what we can do.

**Comment by AaronAtDuo** [comment]
I think we will probably leave this alone unless we find it causing issues for folks.  We're trying to make Github (and our security folks) happy by keeping our dependencies up to date.

**Comment by AaronAtDuo** [comment]
Update 2022-07-25
Retrofit latest is still 2.9.0 so the conflict still exists; but we have had no reports of this causing any issues.

**Comment by AaronAtDuo** [comment]
Update 2022-10-14
or rather, lack of update, since nothing has changed since July.  Still no new version of retrofit, still no reports of issues.

**Comment by AaronAtDuo** [comment]
(Lack of) update 2023-06-30
Still no new version of retrofit and still no reports of any issues.  I'm going to close this out.
