### ISSUE TITLE
Maven artifactId in docs are wrong

### ISSUE THREAD

**Issue by philsmart** [duosecurity/duo_universal_java#2]
The maven artifact described in the documentation (https://duo.com/docs/duoweb-v4#add-the-duo-universal-dependency-to-your-project) is wrong. It needs to reference the duo-universal-sdk not duo-universal-java artifact - there is also no version 1.0.0 on maven central.

**Comment by AaronAtDuo** [comment]
@philsmart Thanks for bringing this up.  We'll address this ASAP.

**Comment by AaronAtDuo** [comment]
@philsmart The website has been updated and has the correct dependency information now.  Thanks for using Duo!
