### ISSUE TITLE
Next version?

### ISSUE THREAD

**Issue by philsmart** [duosecurity/duo_universal_java#33]
Hi, there seems to be several commits to `main` since the last version was released in 2021. I am just wondering if and when there was a plan to release a new version of this library.

**Comment by AaronAtDuo** [comment]
@philsmart That's probably a good idea.  I'll try to get one prioritized.

**Comment by philsmart** [comment]
Thank you.

**Comment by AaronAtDuo** [comment]
@philsmart 1.2.0 has been released and I see it show up in Maven.  The README update should be merged shortly but the release is basically done now.  Thanks for reminding me to get this released!

**Comment by philsmart** [comment]
Many thanks for handling that so quickly.
