### ISSUE TITLE
Reasons for use_duo_code_attribute

### ISSUE THREAD

**Issue by philsmart** [duosecurity/duo_universal_java#5]
Why does the client now default to `use_duo_code_attribute=true` and hence the authorisation code parameter becomes `duo_code` over the previous OAuth2.0 standard `code` name?

**Comment by vbscott** [comment]
Hi, thanks for the question. There were some issues we found with third-party libraries used within thick clients that inappropriately used the `code` parameter.  This caused our implementation to break.  We are investigating a long term solution but in the meantime we introduced `duo_code` as a temporary workaround.  Please feel free to use the `code` attribute as it typically works for any non-thick client use case.

**Comment by philsmart** [comment]
Many thanks, as long as there are no security implications, I can work with it.

**Comment by philsmart** [comment]
There does not appear to be a way to revert to the old behavior with the universal-sdk - `use_duo_code_attribute` is hard coded to true. Is there a plan to allow this to be set.

**Comment by philsmart** [comment]
Just wondering if there was any update on the above?

**Comment by vbscott** [comment]
Thanks for bringing this up.  You're right, we currently are hard coding `use_duo_code_attribute` to be true.  We are tracking this issue internally.

**Comment by AaronAtDuo** [comment]
@philsmart This capability was added in commit ca089b0d8364fd918202828e27de32ee65f7c49f and we'll soon be releasing 1.1 to include it.  Thanks for using Duo and let us know if this does not address your concern.
